### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/report-print-send#108]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] base_report_to_printer - ~~By @sylvain-garancher - #109~~ - By @gdgellatly - #110
- [ ] pingen
- [ ] pingen_document
- [x] printer_tray - Merged in base_report_to_printer - By @gdgellatly - #110 
- [x] printer_zpl2 - By @fmdl - #129

**Comment by gdgellatly** [comment]
#109 Base-report_to_printer
#110 printer_tray -> base_report_to_printer

**Comment by fmdl** [comment]
report-print-send : https://github.com/OCA/report-print-send/pull/129
