### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/report-print-send#300]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
- [ ] base_report_to_printer - By @glitchov - #307
- [x] printer_zpl2 - By @QuocDuong1306 - #331
- [x] remote_report_to_printer - By @etobella - #384

**Comment by micheledic** [comment]
migrated https://github.com/OCA/report-print-send/pull/335

**Comment by yasz** [comment]
thank you for your great work!
