### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/report-print-send#37]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] base_report_to_printer - #52
- [x] printer_tray - By @sylvain-garancher - #65 
- [ ] pingen_document
- [ ] pingen - By @philhug - #42

**Comment by philhug** [comment]
#42

**Comment by Garamotte** [comment]
I'm currently migrating printer_tray to v9.0, but my PR is not ready to be created yet.

**Comment by lasley** [comment]
@sylvain-garancher - tagged you to it

**Comment by Garamotte** [comment]
PR created (waiting for other PRs, but one can begin to look/test it): https://github.com/OCA/report-print-send/pull/65
