### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/report-print-send#59]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] base_report_to_printer - By @sylvain-garancher - #68 
- [ ] pingen
- [ ] pingen_document
- [x] printer_tray - By @sylvain-garancher - #69 
- [ ] printer_zpl2 - By @sylvain-garancher - #81

**Comment by Garamotte** [comment]
I plan to migrate base_report_to_printer and printer_tray once my other PRs are merged :
- Improvement of base_report_ro_printer : #60
- Migration of printer_tray from 8.0 to 9.0 : Not created yet

**Comment by pedrobaeza** [comment]
I have assigned you

**Comment by ghost** [comment]
I also need base_report_to_printer for version 10 and I can help as well.  Do you have a separate fork we collaborate on or has any progress been made?

**Comment by lasley** [comment]
@idncom - Please review #68

**Comment by Garamotte** [comment]
To keep this issue up to date:
- #68 is merged (base_report_to_printer)
- #81 is being reviewed (printer_zpl2)
